name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build
      - name: Pack
        run: |
          dotnet pack DamerauLevensteinDistanceLibGpl/DamerauLevensteinDistanceLibGpl.csproj --output out
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: out/*
